import { useAppSelector } from "@/support/hooks";
import { UserSelector } from "@/redux/slice/users";
import Head from "next/head";

export default function Home() {
  const User = useAppSelector(UserSelector.User);

  return (
    <>
      <Head>
        <title>HGA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <h1>{User?.userName}</h1>
      </div>
    </>
  );
}
